spring:
  redis:
    host: localhost
    port: 6379
    password:
    database: 0
    jedis:
      pool:
        #最大连接数（负值表示没有限制）
        max-active: 100
        #最大空闲链接
        max-idle: 10
        #最小空闲链接
        min-idle: 5
        #最大阻塞时间 负值表示不限制
        max-wait: -1ms

# canal相关配置
canal:
  host: localhost
  port: 11111
  destination: test
  username:
  password:
  subscribe:
  batchSize: 1000

